% You will need to provide the contents of this file yourself as
% it is copyrighted by Steve Gunn.
%
% It is available for ECS students at:
%   https://secure.ecs.soton.ac.uk/notes/TeX/
% 
% Download ecsdocs.zip and find the file ecsproject.cls
% \errmessage{You need to provide the contents of ecsproject.cls}

\ClassError{ecsproject}
  {You need to provide the contents of ecsproject.cls}
  {See the file ecsproject.cls for more information}
\expandafter\@@end
